	git submodule add https://github.com/jiangmiao/auto-pairs.git
	git submodule add https://github.com/kien/ctrlp.vim.git
	git submodule add https://github.com/majutsushi/tagbar
	git submodule add https://github.com/klen/python-mode.git
	git submodule add https://github.com/tomtom/tlib_vim.git
	git submodule add https://github.com/mattn/emmet-vim.git
	git submodule add https://github.com/MarcWeber/vim-addon-mw-utils.git
	git submodule add https://github.com/garbas/vim-snipmate.git
	git submodule add https://github.com/bling/vim-airline
	git submodule add https://github.com/Lokaltog/vim-powerline
	git submodule add https://github.com/powerline/powerline.git
	git submodule add https://github.com/powerline/fonts.git
	git submodule add https://github.com/scrooloose/syntastic.git
	git submodule add https://github.com/powerline/powerline.git
	git submodule add https://github.com/scrooloose/nerdtree.git
	git submodule add https://github.com/MarcWeber/vim-addon-mw-utils.git
	git submodule add https://github.com/scrooloose/snipmate-snippets.git
	git submodule add https://github.com/nathanaelkane/vim-indent-guides.git
	git submodule add https://github.com/Yggdroot/indentLine.git
	git submodule add https://github.com/Yggdroot/indentLine.git
	git submodule add https://github.com/tomasr/molokai.git
	git submodule add https://github.com/tpope/vim-fugitive.git
	git submodule add https://github.com/tpope/vim-sensible.git
	git submodule add https://github.com/powerline/fonts.git
